### ISSUE TITLE
Week 1 | Checklist

### ISSUE THREAD

**Issue by karx** [karx/Spot-me#3]
- [x] Create a checklist
- [x] Explaining the Sprint

- [x] Love Letter (list)
- [x] Breakup Letter (list)

- [ ] Based on our shared understanding, we create a Flowchart/User flow of this product being used.

- [ ] We can shortlist the expert we want to interview 
- [ ] come up with a small questionnaire.
- [ ] also try and schedule this meeting with the expert
